version: '3'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app/Backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/Backend/config/client_secret_1web.json


  frontend:
    build:
      context: ./frontend/digiPrint-Frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    volumes:
      - ./frontend/digiPrint-Frontend:/usr/src/app
    restart: unless-stopped
