services:
  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app


  frontend:
    build:
      context: ./Frontend/digiPrint-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./Frontend/digiPrint-frontend:/app
